version: "3.9"

services:
  exorde:
    build: .
    deploy:
      resources:
        limits:
          cpus: '0.1'
    volumes:
      - ./Launcher.py:/Launcher.py
    restart: unless-stopped
    command: python -u Launcher.py -m 0x82a0a0589d7d68D23a76A74Df7891d4b7FA86179 -l 4
